// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;



namespace MusicDown.Model
{

    public enum SearchType
    {
        Music = 1,
        Alumb = 10,
        Singer = 100,
        MusicList = 1000,
        User = 1002,
        MV = 1004,
        Lyric = 1006,
        Radio = 1009
    }

    public class Artist
    {
        public int img1v1Id { get; set; }
        public string name { get; set; }
        public int id { get; set; }
        public object[] alias { get; set; }
        public int picId { get; set; }
        public string briefDesc { get; set; }
        public string picUrl { get; set; }
        public int albumSize { get; set; }
        public string img1v1Url { get; set; }
        public string trans { get; set; }
        public int musicSize { get; set; }
    }

    public class HMusic
    {
        public string name { get; set; }
        public int id { get; set; }
        public int size { get; set; }
        public string extension { get; set; }
        public int bitrate { get; set; }
        public object dfsId { get; set; }
        public int playTime { get; set; }
        public int sr { get; set; }
        public double volumeDelta { get; set; }
    }

    public class MMusic
    {
        public string name { get; set; }
        public int id { get; set; }
        public int size { get; set; }
        public string extension { get; set; }
        public int bitrate { get; set; }
        public object dfsId { get; set; }
        public int playTime { get; set; }
        public int sr { get; set; }
        public double volumeDelta { get; set; }
    }

    public class LMusic
    {
        public string name { get; set; }
        public int id { get; set; }
        public int size { get; set; }
        public string extension { get; set; }
        public int bitrate { get; set; }
        public object dfsId { get; set; }
        public int playTime { get; set; }
        public int sr { get; set; }
        public double volumeDelta { get; set; }
    }

    public class Artist2
    {
        public int img1v1Id { get; set; }
        public string name { get; set; }
        public int id { get; set; }
        public object[] alias { get; set; }
        public int picId { get; set; }
        public string briefDesc { get; set; }
        public string picUrl { get; set; }
        public int albumSize { get; set; }
        public string img1v1Url { get; set; }
        public string trans { get; set; }
        public int musicSize { get; set; }
    }

    public class Artist3
    {
        public int img1v1Id { get; set; }
        public string name { get; set; }
        public int id { get; set; }
        public object[] alias { get; set; }
        public int picId { get; set; }
        public string briefDesc { get; set; }
        public string picUrl { get; set; }
        public int albumSize { get; set; }
        public string img1v1Url { get; set; }
        public string trans { get; set; }
        public int musicSize { get; set; }
    }

    public class Album
    {
        public object[] songs { get; set; }
        public string name { get; set; }
        public int id { get; set; }
        public string type { get; set; }
        public int size { get; set; }
        public int status { get; set; }
        public string description { get; set; }
        public string tags { get; set; }
        public string[] alias { get; set; }
        public Artist2[] artists { get; set; }
        public int copyrightId { get; set; }
        public object picId { get; set; }
        public string briefDesc { get; set; }
        public Artist3 artist { get; set; }
        public string picUrl { get; set; }
        public string commentThreadId { get; set; }
        public object publishTime { get; set; }
        public string company { get; set; }
        public string blurPicUrl { get; set; }
        public int companyId { get; set; }
        public object pic { get; set; }
        public string[] transNames { get; set; }
    }

    public class BMusic
    {
        public string name { get; set; }
        public int id { get; set; }
        public int size { get; set; }
        public string extension { get; set; }
        public int bitrate { get; set; }
        public object dfsId { get; set; }
        public int playTime { get; set; }
        public int sr { get; set; }
        public double volumeDelta { get; set; }
    }

    public class Audition
    {
        public string name { get; set; }
        public int id { get; set; }
        public int size { get; set; }
        public string extension { get; set; }
        public int bitrate { get; set; }
        public object dfsId { get; set; }
        public int playTime { get; set; }
        public int sr { get; set; }
        public double volumeDelta { get; set; }
    }

    public class Song
    {
        public bool starred { get; set; }
        public double popularity { get; set; }
        public int starredNum { get; set; }
        public int playedNum { get; set; }
        public int dayPlays { get; set; }
        public int hearTime { get; set; }
        public string mp3Url { get; set; }
        public object[] rtUrls { get; set; }
        public string name { get; set; }
        public int id { get; set; }
        public int position { get; set; }
        public int duration { get; set; }
        public int status { get; set; }
        public string[] alias { get; set; }
        public Artist[] artists { get; set; }
        public int copyrightId { get; set; }
        public int score { get; set; }
        public HMusic hMusic { get; set; }
        public MMusic mMusic { get; set; }
        public LMusic lMusic { get; set; }
        public Album album { get; set; }
        public string commentThreadId { get; set; }
        public int fee { get; set; }
        public int mvid { get; set; }
        public int ftype { get; set; }
        public int rtype { get; set; }
        public object rurl { get; set; }
        public string copyFrom { get; set; }
        public BMusic bMusic { get; set; }
        public Audition audition { get; set; }
        public string ringtone { get; set; }
        public string disc { get; set; }
        public int no { get; set; }
        public object crbt { get; set; }
        public object rtUrl { get; set; }
    }

    public class Result
    {
        public string[] queryCorrected { get; set; }
        public int songCount { get; set; }
        public Song[] songs { get; set; }
    }

    public class MusicMeta
    {
        public Result result { get; set; }
        public int code { get; set; }
    }

}
